import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
absolute: "",
default: "Learning Next Js",
template: "%s | Hamza",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{background: "lightblue", padding: "1rem"}}>Header</header>
        {children}

        <footer style={{background: "ghostwhite", padding: "1rem"}}>
          Footer
        </footer>
        </body>
    </html>
  );
}
